INSERT INTO LabelLanguage VALUES ("staffManagement", 0, "Staff Management");
INSERT INTO LabelLanguage VALUES ("leaveManagement", 0, "Leave Management");
INSERT INTO LabelLanguage VALUES ("timetables", 0, "Timetables");
INSERT INTO LabelLanguage VALUES ("eventManagement", 0, "Event Management");
INSERT INTO LabelLanguage VALUES ("registerStaffMember", 0, "Register Staff Member");
INSERT INTO LabelLanguage VALUES ("searchStaffMember", 0, "Search Staff Member");
INSERT INTO LabelLanguage VALUES ("applyForLeave", 0, "Apply for Leave");
INSERT INTO LabelLanguage VALUES ("approveLeave", 0, "Approve Leave");
INSERT INTO LabelLanguage VALUES ("viewLeaveHistory", 0, "View Leave History");
INSERT INTO LabelLanguage VALUES ("createTimetableByTeacher", 0, "Create Timetable by Teacher");
INSERT INTO LabelLanguage VALUES ("createTimetableByClass", 0, "Create Timetable by Class");

INSERT INTO LabelLanguage VALUES ("staffManagement", 1, "කාර්යමණ්ඩලය කළමනාකරණය");
INSERT INTO LabelLanguage VALUES ("leaveManagement", 1, "නිවාඩුව කළමනාකරණය");
INSERT INTO LabelLanguage VALUES ("timetables", 1, "කාලසටහන");
INSERT INTO LabelLanguage VALUES ("eventManagement", 1, "උත්සවය කළමනාකරණය");
INSERT INTO LabelLanguage VALUES ("registerStaffMember", 1, "කාර්යමණ්ඩලය වාර්තාකරන්න");
INSERT INTO LabelLanguage VALUES ("searchStaffMember", 1, "කාර්යමණ්ඩලය සෙවීම");
INSERT INTO LabelLanguage VALUES ("applyForLeave", 1, "නිවාඩු ඉල්ලීම්කිරීම");
INSERT INTO LabelLanguage VALUES ("approveLeave", 1, "නිවාඩු අනුමතකිරීම");
INSERT INTO LabelLanguage VALUES ("viewLeaveHistory", 1, "ඉකුත් වූ නිවාඩු");
INSERT INTO LabelLanguage VALUES ("createTimetableByTeacher", 1, "ගුරුවරයා විසින් කාලසටහන සැකසුම");
INSERT INTO LabelLanguage VALUES ("createTimetableByClass", 1, "පන්තිය විසින් කාලසටහන සැකසුම");